In [ ]:
#siempre lo primero que debo hacer es importar pandas y numpy
import pandas as pd
import numpy as np

In [ ]:
#Ahora subimos el archivo desde drive, ya no tenemos que subirlo desde el ordenador
df_estudiantes = pd.read_csv("/content/drive/MyDrive/StudentsPerformance (1) (1).csv")
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Calculemos el procentaje de participaciÃ³n
df_estudiantes["gender"].value_counts(normalize=True)*100

gender
female    51.8
male      48.2
Name: proportion, dtype: float64

In [ ]:
#Que pasa si lo uso en una columna numerica
df_estudiantes["math score"].value_counts()

math score
65    36
62    35
69    32
59    32
61    27
      ..
24     1
28     1
33     1
18     1
8      1
Name: count, Length: 81, dtype: int64

In [ ]:
#Ordenemos lo datos por el valor de matematicas en ascendente
df_estudiantes.sort_values("math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [ ]:
df_estudiantes= df_estudiantes.sort_values("math score")

In [ ]:
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [ ]:
#IMPORTANTE PARA DESCARGAR DATOS
df_estudiantes.to_csv("matematicas.csv", index=False)

In [ ]:
#Ahora vamos a finalizar de forma descendente
df_estudiantes.sort_values("math score",ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
962,female,group E,associate's degree,standard,none,100,100,100
451,female,group E,some college,standard,none,100,92,97
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [ ]:
#Tambien podemos ordenar los data frame no solo por una columna sino por dos
#Hay que tener en cuenta que organizarÃ¡ por el primer dato y el segunda serÃ¡ dependiente
df_estudiantes.sort_values(["reading score","writing score"], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
106,female,group D,master's degree,standard,none,87,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
957,female,group D,master's degree,standard,none,92,100,100
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
59,female,group C,some high school,free/reduced,none,0,17,10

In [ ]:
df_estudiantes.to_csv("Organizado por lectura.csv", index=False)

In [ ]:
# Para guardar definitivamente, sin creer que se debe volver a reescribir utilizar el siguiente metodo
#De esta manera puerdo guardar los datos con el mÃ©todo Inplace
df_estudiantes.sort_values(["reading score","writing score"], ascending=False,
                           inplace=True)

In [ ]:
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
106,female,group D,master's degree,standard,none,87,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
957,female,group D,master's degree,standard,none,92,100,100
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
59,female,group C,some high school,free/reduced,none,0,17,10

In [ ]:
#Para ordenar valores por texto, para eso usaremos la funciÃ³n lambda
#Con ella convertimos primero los valores en minuscula y luego ordenamos
df_estudiantes.sort_values("race/ethnicity", ascending=True,
                           key=lambda col: col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
837,female,group A,high school,standard,completed,75,82,79
129,female,group A,bachelor's degree,standard,none,51,49,51
467,male,group A,high school,free/reduced,completed,72,67,65
511,male,group A,some high school,standard,none,64,50,43
378,female,group A,some high school,standard,none,71,83,77
...,...,...,...,...,...,...,...,...
186,male,group E,high school,standard,none,80,76,65
968,female,group E,associate's degree,standard,none,68,76,67
269,female,group E,some college,free/reduced,none,71,76,70
926,male,group E,associate's degree,free/reduced,none,64,56,52
881,female,group E,bachelor's degree,standard,completed,71,70,70